# Mini-Projeto Avaliativo: Análise de Varejo
**Aluno:** Izack Serra  
**Turma:** T8

## Visão Geral do Projeto
Este projeto consiste em um pipeline de Engenharia e Análise de Dados simplificado, dividido em etapas lógicas (Sprints):
1. **Geração e Carga de Dados**: Criação de um cenário simulado de compras para testes e ingestão do arquivo.
2. **Diagnóstico dos Dados**: Identificação de inconsistências, valores nulos, registros duplicados e anomalias estruturais.
3. **Tratamento e Limpeza**: Correção ativa dos problemas encontrados (strings desalinhadas, valores nulos em colunas categóricas e numéricas, remoção de duplicatas).
4. **Análise de Dados**: Agrupamentos, faturamentos, cálculo de métricas de negócio e cálculo do Ticket Médio.
5. **Exportação**: Gravação do resultado higienizado em um novo arquivo pronto para consumo.

In [ ]:
import pandas as pd
import numpy as np


np.random.seed(42)
n = 300
df_simulado = pd.DataFrame({
    'id_cliente': [f"C{i:03d}" for i in range(1, n+1)],
    'nome': np.random.choice(['Ana Silva', 'carlos souza', '  Maria Oliveira ', 'JOAO PEREIRA', None, '   '], n),
    'idade': np.random.choice([25, 30, 35, 40, 45, None, 150], n),
    'genero': np.random.choice(['Feminino', 'Masculino', 'F', 'M', None], n),
    'categoria': np.random.choice(['Eletrônicos', 'Vestuário', 'Alimentação', 'Beleza', None], n),
    'valor_compra': np.random.choice([150.0, 45.5, 300.0, 1200.0, 89.9, None, -10.0], n),
    'quantidade': np.random.choice([1, 2, 3, 4, None], n)
})
df_simulado = pd.concat([df_simulado, df_simulado.iloc[:10]], ignore_index=True) # Adiciona duplicatas para o diagnóstico
df_simulado.to_csv('varejo.csv', index=False)


df_original = pd.read_csv('varejo.csv')
print("Arquivo 'varejo.csv' criado e lido com sucesso!")
print(f"Dimensões: {df_original.shape[0]} linhas e {df_original.shape[1]} colunas.")
display(df_original.head())

Arquivo 'varejo.csv' criado e lido com sucesso!
Dimensões: 310 linhas e 7 colunas.

,id_cliente,nome,idade,genero,categoria,valor_compra,quantidade
0,C001,JOAO PEREIRA,NaN,NaN,Eletrônicos,NaN,1.0
1,C002,NaN,25.0,Masculino,Beleza,-10.0,3.0
2,C003,Maria Oliveira,35.0,NaN,Vestuário,300.0,2.0
3,C004,NaN,25.0,F,Vestuário,300.0,3.0
4,C005,NaN,45.0,NaN,Eletrônicos,300.0,NaN

## Etapa 1: Diagnóstico Situacional da Base de Dados
Nesta etapa, o objetivo é mapear detalhadamente a integridade do arquivo lido. Analisamos:
- As primeiras linhas para validação visual preliminar.
- A volumetria dos dados (número de registros e atributos).
- Tipagem inferida pelo Pandas para garantir coerência.
- Presença e volume de valores faltantes (`NaN`).
- Presença de duplicatas e dados textuais com espaços indesejados.

In [ ]:
import pandas as pd


df_original = pd.read_csv('varejo.csv')


print("--- PRIMEIRAS LINHAS ---")
display(df_original.head())


print(f"\nDimensões da base: {df_original.shape[0]} linhas e {df_original.shape[1]} colunas.")


print("\nNomes e Tipos de Dados:")
print(df_original.dtypes)


print("\nValores ausentes por coluna:")
print(df_original.isnull().sum())


print(f"\nLinhas duplicadas confirmadas: {df_original.duplicated().sum()}")


vazios = df_original['nome'].astype(str).str.strip().eq("").sum()
print(f"Textos vazios ou só com espaços na coluna 'nome': {vazios}")

--- PRIMEIRAS LINHAS ---

,id_cliente,nome,idade,genero,categoria,valor_compra,quantidade
0,C001,JOAO PEREIRA,NaN,NaN,Eletrônicos,NaN,1.0
1,C002,NaN,25.0,Masculino,Beleza,-10.0,3.0
2,C003,Maria Oliveira,35.0,NaN,Vestuário,300.0,2.0
3,C004,NaN,25.0,F,Vestuário,300.0,3.0
4,C005,NaN,45.0,NaN,Eletrônicos,300.0,NaN

Dimensões da base: 310 linhas e 7 colunas.

Nomes e Tipos de Dados:
id_cliente       object
nome             object
idade           float64
genero           object
categoria        object
valor_compra    float64
quantidade      float64
dtype: object

Valores ausentes por coluna:
id_cliente       0
nome            43
idade           48
genero          80
categoria       58
valor_compra    45
quantidade      68
dtype: int64

Linhas duplicadas confirmadas: 10
Textos vazios ou só com espaços na coluna 'nome': 46

## Etapa 2: Desenvolvimento de Funções de Limpeza e Agregação
Nesta etapa, criamos funções modulares e reutilizáveis utilizando boas práticas de programação:
- `tratar_dados_varejo(df)`: Realiza a limpeza de forma determinística, padroniza strings para o formato Title Case, preenche nulos categóricos com rótulos padrão, remove duplicatas e substitui valores ausentes ou inconsistentes na coluna financeira utilizando a mediana.
- `gerar_resumo_estatistico(df)`: Extrai as principais métricas de faturamento e volume agregadas do projeto.

In [ ]:
def tratar_dados_varejo(df):
    """Função de tratamento com parâmetro e retorno"""
    df_tratado = df.copy()


    df_tratado = df_tratado.drop_duplicates()


    if 'nome' in df_tratado.columns:
        df_tratado['nome'] = df_tratado['nome'].fillna("Cliente Desconhecido")
        df_tratado['nome'] = df_tratado['nome'].astype(str).str.strip().str.title()
        df_tratado.loc[df_tratado['nome'] == "", 'nome'] = "Cliente Desconhecido"


    if 'genero' in df_tratado.columns:
        df_tratado['genero'] = df_tratado['genero'].fillna("Não Informado")
        df_tratado['genero'] = df_tratado['genero'].replace({"F": "Feminino", "M": "Masculino"})


    if 'categoria' in df_tratado.columns:
        df_tratado['categoria'] = df_tratado['categoria'].fillna("Outros")


    if 'valor_compra' in df_tratado.columns:
        df_tratado['valor_compra'] = pd.to_numeric(df_tratado['valor_compra'], errors='coerce')
        mediana = df_tratado['valor_compra'].median()
        df_tratado['valor_compra'] = df_tratado['valor_compra'].fillna(mediana).abs()

    return df_tratado

def gerar_resumo_estatistico(df):
    """Função de resumo estatístico com parâmetro e retorno"""
    resumo = {
        "total_registros": len(df),
        "faturamento_total": float(df['valor_compra'].sum()),
        "ticket_medio": float(df['valor_compra'].mean())
    }
    return resumo


df_limpo = tratar_dados_varejo(df_original)
resumo_executivo = gerar_resumo_estatistico(df_limpo)

print(f"Registros antes da limpeza: {len(df_original)}")
print(f"Registros após a limpeza: {len(df_limpo)}")
print("\nResumo Executivo Gerado:")
print(resumo_executivo)

Registros antes da limpeza: 310
Registros após a limpeza: 300

Resumo Executivo Gerado:
{'total_registros': 300, 'faturamento_total': 69111.00000000001, 'ticket_medio': 230.37000000000006}

## Etapa 3: Exploração Estatística e Análises Agrupadas
Após a higienização completa dos dados, aplicamos agrupamentos estratégicos para responder perguntas cruciais de negócio:
- Resumo estatístico descritivo dos valores de compra (contagem, ticket médio, extremos).
- Filtro de clientes de alto valor (compras acima de R$ 100,00).
- Quantidade de transações realizadas por cada categoria de produto.
- Faturamento total segmentado por gênero dos consumidores.

In [ ]:
coluna = 'valor_compra'


print(f"Estatísticas da coluna '{coluna}':")
print(f" - Contagem válida: {df_limpo[coluna].count()}")
print(f" - Média (Ticket Médio): R$ {df_limpo[coluna].mean():.2f}")
print(f" - Mínimo: R$ {df_limpo[coluna].min():.2f}")
print(f" - Máximo: R$ {df_limpo[coluna].max():.2f}")


df_filtrado = df_limpo[df_limpo['valor_compra'] > 100.00]
print(f"\nRegistros com valor superior a R$ 100,00: {len(df_filtrado)}")


print("\n--- Agrupamento 1: Compras por Categoria ---")
agrp_cat = df_limpo.groupby('categoria')['id_cliente'].count().reset_index()
agrp_cat.columns = ['Categoria', 'Quantidade de Compras']
print(agrp_cat)


print("\n--- Agrupamento 2: Faturamento por Gênero ---")
agrp_gen = df_limpo.groupby('genero')['valor_compra'].sum().reset_index()
agrp_gen.columns = ['Gênero', 'Faturamento Total (R$)']
print(agrp_gen)

Estatísticas da coluna 'valor_compra':
 - Contagem válida: 300
 - Média (Ticket Médio): R$ 230.37
 - Mínimo: R$ 10.00
 - Máximo: R$ 1200.00

Registros com valor superior a R$ 100,00: 122

--- Agrupamento 1: Compras por Categoria ---
     Categoria  Quantidade de Compras
0  Alimentação                     61
1       Beleza                     58
2  Eletrônicos                     69
3       Outros                     57
4    Vestuário                     55

--- Agrupamento 2: Faturamento por Gênero ---
          Gênero  Faturamento Total (R$)
0       Feminino                 25663.3
1      Masculino                 24913.9
2  Não Informado                 18533.8

In [ ]:
print("--- Comparação: Valor Médio de Compra por Gênero ---")
agrp_media_gen = df_limpo.groupby('genero')['valor_compra'].mean().reset_index()
agrp_media_gen.columns = ['Gênero', 'Valor Médio de Compra (R$)']
display(agrp_media_gen)

--- Comparação: Valor Médio de Compra por Gênero ---

          Gênero  Valor Médio de Compra (R$)
0       Feminino                  219.344444
1      Masculino                  230.684259
2  Não Informado                  247.117333

## Etapa 4: Exportação da Base Tratada
O passo final consiste em persistir e salvar o DataFrame completamente saneado e estruturado. Exportamos os dados sem o índice numérico do Pandas para o arquivo `varejo_limpo.csv`, garantindo que analistas ou ferramentas de BI (como Power BI ou Tableau) consumam um arquivo íntegro e sem ruídos.

In [19]:

arquivo_saida = "varejo_limpo.csv"
df_limpo.to_csv(arquivo_saida, index=False)

print(f"Base tratada exportada com sucesso para '{arquivo_saida}'!")

Base tratada exportada com sucesso para 'varejo_limpo.csv'!

## Conclusão e Principais Insights

Após a conclusão de todas as etapas (Sprints) de engenharia e análise de dados, destacamos os seguintes pontos chave do projeto:

1. **Qualidade dos Dados**: A etapa de diagnóstico identificou problemas severos como duplicatas estruturais, nomes com espaços inconsistentes e valores nulos em mais de 15% das colunas fundamentais. A aplicação da limpeza determinística garantiu a confiabilidade dos relatórios subsequentes.
2. **Faturamento Geral e Ticket Médio**: O faturamento total consolidado do período foi de **R$ 69.111,00**, com um ticket médio geral de aproximadamente **R$ 230,37** por transação.
3. **Dinâmica de Gênero**:
   - O público **Feminino** lidera o volume total de faturamento com **R$ 25.663,30**.
   - No entanto, individualmente, o público **Masculino** possui um consumo médio por compra ligeiramente superior (**R$ 230,68** frente a **R$ 219,34**).
4. **Performance de Categorias**: A categoria de **Eletrônicos** se destacou como a de maior atividade em quantidade de compras (**69 transações**), demonstrando grande relevância para a receita do negócio.

Com a base limpa exportada para `varejo_limpo.csv`, o negócio está agora pronto para realizar modelagens preditivas estáveis ou alimentar dashboards corporativos seguros.